### ISSUE TITLE
 java.security.SignatureException and android.security.KeyStoreException

### ISSUE THREAD

**Issue by AdamEmbdt** [chamodanethra/biometric_signature#24]
Hey, we have reported by Crashlytics those two exception by your package (version 5.1.1).

These are the logs:

          Caused by java.security.SignatureException: android.security.KeyStoreException: Key user not authenticated (internal Keystore code: -26 message: system/security/keystore2/src/operation.rs:850: KeystoreOperation::finish

Caused by:
    0: system/security/keystore2/src/operation.rs:426: Finish failed.
    1: Error::Km(r#KEY_USER_NOT_AUTHENTICATED)) (public error code: 2 internal Keystore code: -26)
       at android.security.keystore2.AndroidKeyStoreSignatureSpiBase.engineSign(AndroidKeyStoreSignatureSpiBase.java:332)
       at java.security.Signature$Delegate.engineSign(Signature.java:1422)
       at java.security.Signature.sign(Signature.java:743)
       at com.chamoda.nethra.biometric_signature.BiometricSignaturePlugin$createSignature$1.onAuthenticationSucceeded(BiometricSignaturePlugin.kt:158)
       at androidx.biometric.BiometricFragment.lambda$sendSuccessToClient$8(BiometricFragment.java:919)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8391)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:640)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
       
--------------------------------------

 Caused by android.security.KeyStoreException: Key user not authenticated (internal Keystore code: -26 message: system/security/keystore2/src/operation.rs:850: KeystoreOperation::finish

Caused by:
    0: system/security/keystore2/src/operation.rs:426: Finish failed.
    1: Error::Km(r#KEY_USER_NOT_AUTHENTICATED))
       at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:386)
       at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
       at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
       at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
       at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
       at android.security.keystore2.AndroidKeyStoreSignatureSpiBase.engineSign(AndroidKeyStoreSignatureSpiBase.java:328)
       at java.security.Signature$Delegate.engineSign(Signature.java:1422)
       at java.security.Signature.sign(Signature.java:743)
       at com.chamoda.nethra.biometric_signature.BiometricSignaturePlugin$createSignature$1.onAuthenticationSucceeded(BiometricSignaturePlugin.kt:158)
       at androidx.biometric.BiometricFragment.lambda$sendSuccessToClient$8(BiometricFragment.java:919)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8391)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:640)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
        

I haven't been able to replicate this yet. Hopefully you'll be able to find the mistake based on this :)

**Comment by chamodanethra** [comment]
@AdamEmbdt , let me know whether the issue persists with the latest version of the plugin: https://pub.dev/packages/biometric_signature/versions/5.1.3

Thank you.

**Comment by AdamEmbdt** [comment]
I will, thanks !
